<?php

namespace ContainerFygxEGs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHtmlSanitizer_Extension_IframeService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'html_sanitizer.extension.iframe' shared service.
     *
     * @return \HtmlSanitizer\Extension\Iframe\IframeExtension
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/tgalopin/html-sanitizer/src/Extension/ExtensionInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/tgalopin/html-sanitizer/src/Extension/Iframe/IframeExtension.php';

        return $container->privates['html_sanitizer.extension.iframe'] = new \HtmlSanitizer\Extension\Iframe\IframeExtension();
    }
}
