<?php

namespace ContainerFygxEGs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTwig_Markdown_LeagueCommonMarkConverterFactoryService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'twig.markdown.league_common_mark_converter_factory' shared service.
     *
     * @return \Twig\Extra\TwigExtraBundle\LeagueCommonMarkConverterFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/twig/extra-bundle/LeagueCommonMarkConverterFactory.php';

        return $container->privates['twig.markdown.league_common_mark_converter_factory'] = new \Twig\Extra\TwigExtraBundle\LeagueCommonMarkConverterFactory(new RewindableGenerator(function () use ($container) {
            return new \EmptyIterator();
        }, 0));
    }
}
