<?php

namespace ContainerFygxEGs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTwig_Markdown_DefaultService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'twig.markdown.default' shared service.
     *
     * @return \Twig\Extra\Markdown\LeagueMarkdown
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/twig/markdown-extra/MarkdownInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/twig/markdown-extra/LeagueMarkdown.php';

        return $container->privates['twig.markdown.default'] = new \Twig\Extra\Markdown\LeagueMarkdown(($container->privates['twig.markdown.league_common_mark_converter'] ?? $container->load('getTwig_Markdown_LeagueCommonMarkConverterService')));
    }
}
