<?php

namespace ContainerXfNUUVj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHtmlSanitizer_DefaultService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'html_sanitizer.default' shared service.
     *
     * @return \HtmlSanitizer\SanitizerInterface
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/tgalopin/html-sanitizer/src/SanitizerInterface.php';

        return $container->privates['html_sanitizer.default'] = ($container->privates['html_sanitizer.builder'] ?? $container->load('getHtmlSanitizer_BuilderService'))->build(['extensions' => [0 => 'basic', 1 => 'list', 2 => 'table', 3 => 'image', 4 => 'code']]);
    }
}
