<?php

namespace ContainerXfNUUVj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMomentFormatConverterService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Utils\MomentFormatConverter' shared autowired service.
     *
     * @return \App\Utils\MomentFormatConverter
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Utils/MomentFormatConverter.php';

        return $container->privates['App\\Utils\\MomentFormatConverter'] = new \App\Utils\MomentFormatConverter();
    }
}
