<?php

namespace ContainerXfNUUVj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getValidatorService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Utils\Validator' shared autowired service.
     *
     * @return \App\Utils\Validator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Utils/Validator.php';

        return $container->privates['App\\Utils\\Validator'] = new \App\Utils\Validator();
    }
}
