<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFygxEGs\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFygxEGs/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerFygxEGs.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerFygxEGs\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerFygxEGs\App_KernelTestDebugContainer([
    'container.build_hash' => 'FygxEGs',
    'container.build_id' => 'aca71e3d',
    'container.build_time' => 1651319931,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFygxEGs');
