<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWKxUgDW\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWKxUgDW/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWKxUgDW.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWKxUgDW\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWKxUgDW\App_KernelDevDebugContainer([
    'container.build_hash' => 'WKxUgDW',
    'container.build_id' => 'c1b97325',
    'container.build_time' => 1651319260,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWKxUgDW');
