<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7pyb2c7\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7pyb2c7/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container7pyb2c7.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container7pyb2c7\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container7pyb2c7\App_KernelDevDebugContainer([
    'container.build_hash' => '7pyb2c7',
    'container.build_id' => '98b47f8a',
    'container.build_time' => 1651310311,
], __DIR__.\DIRECTORY_SEPARATOR.'Container7pyb2c7');
