<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTJd28SG\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTJd28SG/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTJd28SG.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTJd28SG\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTJd28SG\App_KernelDevDebugContainer([
    'container.build_hash' => 'TJd28SG',
    'container.build_id' => 'cb52f5bf',
    'container.build_time' => 1651316272,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTJd28SG');
